module.exports = [
    '',
    'system-requirements',
    'install-windows',
    'install-linux',
    'install-macos',
    'feature-matrix',
    'changelog',
    'connection',
    'dataview',
    'designer-schema',
    'designer-model',
    'designer-sqlview',
    'editor',
    'visual-sql-builder',
    'sqlite',
    'faq',
]